version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: krishi
      POSTGRES_PASSWORD: krishi
      POSTGRES_DB: krishi_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://krishi:krishi@db:5432/krishi_db
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
volumes:
  db_data:
